### ISSUE TITLE
Move this repository to Tox organization

### ISSUE THREAD

**Issue by urras** [pwnsdx/Tox-Website#13]
Sooner or later, we need to move the site to the official [Tox organization](https://github.com/Tox), so that website maintainers can push changes as needed. Also, people would be more likely to contribute translations if this repository was an official Tox repo.

**Comment by pwnsdx** [comment]
I agree! What about Tox-Website-2 for the repo name?

**Comment by urras** [comment]
I was thinking about maybe Tox-Website-Next or Tox-Website-Beta, but its your call

**Comment by pwnsdx** [comment]
Next/Beta looks better indeed :p
