### ISSUE TITLE
Black Space in the body

### ISSUE THREAD

**Issue by anuragagarwal561994** [pwnsdx/Tox-Website#16]
In Firefox it appears in the desktop screen size as well as for smaller screen sizes
![screenshot from 2015-03-21 21 29 02](https://cloud.githubusercontent.com/assets/6075379/6765742/bdd2678a-d012-11e4-9695-c693c6be9903.png)

In Chrome it appears in the smaller screen size
![screenshot from 2015-03-21 21 35 40](https://cloud.githubusercontent.com/assets/6075379/6765747/dc477232-d012-11e4-9f2f-612c05a2a315.png)

**Comment by pwnsdx** [comment]
Probably because of this: https://github.com/pwnsdx/Tox-Website/pull/12

**Comment by anuragagarwal561994** [comment]
Yes #12 plays a role in this issue but not completely. There are 3 things that are overflowing:
1. The header as you said
2. The right image in the second section (first aside.tObject)
3. The downloadNow section (second aside.tObject)

Setting the margin-left: 0px in the header and overflow: hidden in the aside could solve the problem but for smaller screen sizes certain elements on the screen will get off which will not look good. Also when the screen size goes smaller, overlapping of certain objects happens which does not give a nice look. Have a look at this screen shot:

![screenshot from 2015-03-22 15 55 37](https://cloud.githubusercontent.com/assets/6075379/6768966/110f37e0-d0ac-11e4-90a9-a633e10f0649.png)

Thus the site needs to be more responsive to smaller screen sizes. Suggest me some things based on the responsiveness and I will correct the issues in my next PR.

**Comment by pwnsdx** [comment]
I know that the website have lacks with responsive. I should work on it but I unfortunately don't have time to do so. There is no suggestions in particular except the fact the the website should fit in all devices. You are welcome.

**Comment by anuragagarwal561994** [comment]
Sorry I closed the issue by mistake. I can add responsiveness to like all the other divs but I would need suggestions for the second section (with images).

**Comment by pwnsdx** [comment]
As there is no official mobile app, I suggest to hide the divs and disable actions of it in JS.
