### ISSUE TITLE
Scrolling not enabled before clicking down arrow

### ISSUE THREAD

**Issue by m3hr** [pwnsdx/Tox-Website#2]
usability issue

**Comment by pwnsdx** [comment]
This is the normal behavior.

**Comment by davidak** [comment]
i also noticed that.

i would rather scroll than click but you forced me to. thats not nice.

**Comment by pwnsdx** [comment]
Hmm, maybe we should unlock the scroll by default then.

**Comment by urras** [comment]
Yeah, a lot of people have complained about it not letting them scroll

**Comment by stqism** [comment]
This is fixed in the latest code.
