### ISSUE TITLE
grammar-ish

### ISSUE THREAD

**Issue by Balloon2mars** [pwnsdx/Tox-Website#22]
Beta.tox.im

"make secure tox to tox audio and video calls. Securely."
 ^no
"make tox to tox audio and video calls. Securely!"
 ^yes

**Comment by zetok** [comment]
``make secure tox to tox audio and video calls.`` ?

**Comment by pwnsdx** [comment]
I personally would write "Make Tox to Tox audio and video calls. Securely."

**Comment by pwnsdx** [comment]
Fixed: https://github.com/pwnsdx/Tox-Website/commit/142114108df1ddf846141329be7030cbf2cef3f3
