### ISSUE TITLE
Font of Operating Systems at bottom not loading

### ISSUE THREAD

**Issue by m3hr** [pwnsdx/Tox-Website#3]
in Chrome or FF

**Comment by urras** [comment]
Hmm, do you think we can get a screenshot?

**Comment by m3hr** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/700679/6697488/2fa8e7c0-ccc7-11e4-8139-5586a14f5818.png)

Those letters should be in the same font. This is Ubuntu 14.10 by the way.

**Comment by urras** [comment]
Yeah, this is an issue that I've noticed on Firefox, but not Chrome. I might have to do some digging though to find the root cause, unless @stqism knows whats up

**Comment by pwnsdx** [comment]
You must apply the following class to each text:
font FiraSans regular

For example:
<span class="font FiraSans regular">Win32</span>
