### ISSUE TITLE
IE8=> Banner

### ISSUE THREAD

**Issue by urras** [pwnsdx/Tox-Website#4]
On Tox.im, we currently have a banner to warn users if they're using an unsupported browser (IE 8 or lower). Can we get something similar on the new site?

**Comment by pwnsdx** [comment]
Great idea. I could add this as soon as I will be available again.

**Comment by urras** [comment]
Awesome, thank you :+1:

**Comment by urras** [comment]
@pwnsdx Any reason why this was reopened?

**Comment by pwnsdx** [comment]
Hello,

Because it isn't done yet?

S.
