### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by urras** [pwnsdx/Tox-Website#6]
Many users have translated tox.im into different languages. Is there any way that we can retain some of the current translations at https://github.com/Tox/Tox-Website? 
Also, an easy way for users to submit translations would be helpful.

**Comment by pwnsdx** [comment]
Yup. At the end I think as the website is not ready for multiple languages yet.

For the easy-way I can suggest Transifex. Everyone is using it.

**Comment by stqism** [comment]
@pwnsdx It's free for open source, so that actually sounds great.

**Comment by Spagy** [comment]
It looks as though Transifex has been set up and beta.tox.im has translations available. Should this be closed now?

**Comment by urras** [comment]
Sure
